#!/bin/sh

# CUPANG : CUrl dibikin gamPANG
# ====================
# uses jq ( for json highlighting )
# thanks to beadlist for the guide!
# by padulkemid
# ====================
# HOW TO USE
# ====================
# 1. comment/un-comment functions on the 'script' tag below ( end of file )
# 2. execute this script by running : 
#      chmod +x (name_of_this_script, default is pcl)
#      ./pcl
# ====================

# functions
create_user() {
  curl -X POST \
    -H 'Content-Type: application/json' \
    -d @$1 \
    -v "$URL/register"
}

login_user() {
  curl -X POST \
    -H 'Content-Type: application/json' \
    -d @$1 \
    -v "$URL/login"
}

list(){
  curl -X GET \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -v "$URL/tasks"
}

list_id() {
  curl -X GET \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -v "$URL/tasks/$1"
}

create_task() {
  curl -X POST \
    -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -d @$2 \
    -v "$URL/tasks"
}

api_test() {
  curl -H 'Content-Type: application/json' \
    -H "token: $TOKEN" \
    -v "$URL/news/$1"
}


# address
URL="http://localhost:3000"
TOKEN=$(login_user test.json | jq -r .token)

# script
# I used a file called test.json to send the request
# by default, it searches for this
# ====================================================
# create_user test.json | jq '.'
# login_user test.json | jq '.'
# create_task test.json test1.json | jq '.'
list | jq '.'
# login_user test.json | jq -r .token
# list_todo_by_id 6 | jq '.'
# api_test "id" | jq '.'
